### PR TITLE
Update laravel support up to 9

### PR DESCRIPTION
**Pull request by pionl**
based on #4 - I've tested it on the same code as Jakub

### CODE REVIEW

**Comment by pionl** [comment]
Rebased

**Comment by atorscho** [comment]
Thank you for the upgrade :)

**Comment by pionl** [comment]
Np :) but i dont see the changes in v2 branch ( https://github.com/atorscho/laravel-breadcrumbs/blob/v2/composer.json). The merge commit landed into the PR branch

**Comment by pionl** [comment]
Fixed invalid json https://github.com/pionl/crumbs/commit/b223619b61d6811dd487cf9ae51d29712858befc

**Pull request merged**
